{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "themis.postgres.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "themis.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresql.storage.size }}
  {{- with .Values.postgresql.storage.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
{{- end }}
