apiVersion: v1
kind: Secret
metadata:
  name: {{ include "themis.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "themis.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ required "backend.jwtSecret is required" .Values.backend.jwtSecret | quote }}
  {{- if .Values.postgresql.enabled }}
  postgres-password: {{ required "postgresql.auth.password is required" .Values.postgresql.auth.password | quote }}
  {{- end }}
