#!/usr/bin/env bash
# Themis installer, interactive setup for on-premise deployments.
# Usage: curl -fsSL https://raw.githubusercontent.com/YOUR-ORG/themis/main/deploy/install.sh | bash
#        or: ./deploy/install.sh [non-interactive]
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
NON_INTERACTIVE="${1:-}"

RED='\033[0;31m'; YELLOW='\033[1;33m'; GREEN='\033[0;32m'; CYAN='\033[0;36m'; NC='\033[0m'
info()    { echo -e "${CYAN}[themis]${NC} $*"; }
success() { echo -e "${GREEN}[themis]${NC} $*"; }
warn()    { echo -e "${YELLOW}[themis]${NC} $*"; }
die()     { echo -e "${RED}[themis] ERROR:${NC} $*" >&2; exit 1; }

# Prerequisites
check_deps() {
    local missing=()
    for cmd in docker curl openssl; do
        command -v "$cmd" &>/dev/null || missing+=("$cmd")
    done

    # docker compose v2 (plugin) or docker-compose v1
    if ! docker compose version &>/dev/null 2>&1 && ! command -v docker-compose &>/dev/null; then
        missing+=("docker-compose")
    fi

    if [[ ${#missing[@]} -gt 0 ]]; then
        die "Missing required tools: ${missing[*]}\nInstall Docker Desktop or Docker Engine + Compose, then re-run this script."
    fi

    # docker compose shim
    if ! docker compose version &>/dev/null 2>&1; then
        COMPOSE="docker-compose"
    else
        COMPOSE="docker compose"
    fi
    export COMPOSE
}

# Prompt helper
ask() {
    local prompt="$1" default="$2" var_name="$3"
    if [[ "$NON_INTERACTIVE" == "non-interactive" ]]; then
        eval "$var_name=\"$default\""
        return
    fi
    read -rp "$(echo -e "${CYAN}?${NC} ${prompt} [${default}]: ")" input
    eval "$var_name=\"${input:-$default}\""
}

ask_secret() {
    local prompt="$1" var_name="$2"
    if [[ "$NON_INTERACTIVE" == "non-interactive" ]]; then
        eval "$var_name=\"$(openssl rand -hex 48)\""
        return
    fi
    read -rsp "$(echo -e "${CYAN}?${NC} ${prompt} (leave blank to auto-generate): ")" input
    echo
    if [[ -z "$input" ]]; then
        eval "$var_name=\"$(openssl rand -hex 48)\""
        info "JWT secret auto-generated."
    else
        eval "$var_name=\"$input\""
    fi
}

# Main
main() {
    echo
    echo -e "${CYAN}╔══════════════════════════════════╗${NC}"
    echo -e "${CYAN}║  Themis On-Premise Installer      ║${NC}"
    echo -e "${CYAN}╚══════════════════════════════════╝${NC}"
    echo

    check_deps

    ENV_FILE="$REPO_ROOT/.env"

    if [[ -f "$ENV_FILE" ]]; then
        warn ".env already exists at $ENV_FILE"
        if [[ "$NON_INTERACTIVE" != "non-interactive" ]]; then
            read -rp "$(echo -e "${YELLOW}?${NC} Overwrite it? [y/N]: ")" overwrite
            [[ "${overwrite,,}" == "y" ]] || { info "Keeping existing .env. Run 'docker compose up -d' to start."; exit 0; }
        fi
    fi

    info "Configuring Themis..."
    echo

    # Networking
    ask "HTTP port (the port your browser will use)" "80" HTTP_PORT

    # Database
    ask "PostgreSQL password" "$(openssl rand -hex 16)" POSTGRES_PASSWORD
    ask "PostgreSQL database name" "themis" POSTGRES_DB
    ask "PostgreSQL username" "themis" POSTGRES_USER

    # Security
    ask_secret "JWT secret" JWT_SECRET

    # App settings
    ask "Max golden config versions to retain per device" "10" MAX_GOLDEN_CONFIGS
    ask "Log level (error/warn/info/debug)" "info" LOG_LEVEL

    # HTTPS
    DOMAIN=""
    LETSENCRYPT_EMAIL=""
    if [[ "$NON_INTERACTIVE" != "non-interactive" ]]; then
        read -rp "$(echo -e "${CYAN}?${NC} Enable HTTPS with Let's Encrypt? [y/N]: ")" want_https
        if [[ "${want_https,,}" == "y" ]]; then
            ask "Domain name (e.g. themis.example.com)" "" DOMAIN
            ask "Let's Encrypt email" "" LETSENCRYPT_EMAIL
        fi
    fi

    # Write .env
    cat > "$ENV_FILE" <<EOF
# Generated by deploy/install.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

JWT_SECRET=${JWT_SECRET}

POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=${POSTGRES_DB}

HTTP_PORT=${HTTP_PORT}
BACKEND_PORT=8080

MAX_GOLDEN_CONFIGS=${MAX_GOLDEN_CONFIGS}
RUST_LOG=themis_backend=${LOG_LEVEL}
EOF

    if [[ -n "$DOMAIN" ]]; then
        cat >> "$ENV_FILE" <<EOF

DOMAIN=${DOMAIN}
LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
EOF
    fi

    success ".env written to $ENV_FILE"
    echo

    # Build or pull images
    if [[ "$NON_INTERACTIVE" != "non-interactive" ]]; then
        read -rp "$(echo -e "${CYAN}?${NC} Build images from source (B) or pull pre-built from registry (P)? [B/p]: ")" build_choice
    else
        build_choice="b"
    fi

    cd "$REPO_ROOT"

    if [[ "${build_choice,,}" == "p" ]]; then
        # Pull mode. Requires IMAGE_REGISTRY / IMAGE_TAG to be set.
        info "Pulling pre-built images..."
        $COMPOSE -f docker-compose.prod.yml pull
        UP_FILE="-f docker-compose.prod.yml"
    else
        info "Building images from source (this takes a few minutes)..."
        $COMPOSE build
        UP_FILE=""
    fi

    if [[ -n "$DOMAIN" ]]; then
        info "Starting with HTTPS support..."
        $COMPOSE $UP_FILE -f docker-compose.https.yml up -d
    else
        $COMPOSE $UP_FILE up -d
    fi

    echo
    success "Themis is running!"
    echo
    echo -e "  ${CYAN}Frontend:${NC}  http://$(hostname -I | awk '{print $1}'):${HTTP_PORT}"
    echo -e "  ${CYAN}API:${NC}       http://$(hostname -I | awk '{print $1}'):8080/api"
    echo
    echo -e "  Create your first admin account:"
    echo -e "    Open the URL above and register. The first user gets admin role automatically."
    echo
    echo -e "  Useful commands:"
    echo -e "    ${CYAN}$COMPOSE logs -f backend${NC}       , tail backend logs"
    echo -e "    ${CYAN}$COMPOSE down${NC}                  , stop all services"
    echo -e "    ${CYAN}$COMPOSE pull && $COMPOSE up -d${NC} , upgrade to latest"
    echo
}

main "$@"
